apiVersion: v1
kind: ConfigMap
metadata:
  name: web-server-nginx-conf
data:
  index.html: |

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Document</title>
    </head>
    <body>
      <h1>Code.education Rocks.</h1>
    </body>
    </html>