steps:

- id: "Rodando install"
  name: "gcr.io/cloud-builders/go"
  args: ["install", "desafio-go"]
  env: ["GOPATH=."]

- id: "Rodando Test"
  name: "gcr.io/cloud-builders/go"
  args: ["test", "desafio-go"]
  env: ["GOPATH=."]

- id: "Rodando Build"
  name: "gcr.io/cloud-builders/docker"
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-go:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-go:$SHORT_SHA'
  - '.'
  #args: ["build", "--tag=gcr.io/$PROJECT_ID/desafio-ci-sum:latest", "."]

images:
- 'gcr.io/$PROJECT_ID/desafio-go:latest'
- 'gcr.io/$PROJECT_ID/desafio-go:$SHORT_SHA'
tags: ['cloud-builders-community']