apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-go

spec:
  replicas: 1

  selector:
    matchLabels:
      app: desafio-go
  
  template:
    metadata:
      labels:
        app: desafio-go
    spec:
      containers:
      - name: desafio-go
        image: robsantossilva/desafio-go-codeeducation:latest
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: desafio-go-service
  labels:
    app: desafio-go-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
  selector:
    app: desafio-go